# Generated by Django 2.2.1 on 2019-05-13 20:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=16)),
                ('_from', models.CharField(max_length=16)),
                ('sid', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('_to', models.CharField(max_length=16)),
                ('twilio_metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('content', models.FileField(upload_to='fax-media/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
