# Generated by Django 2.2.1 on 2019-05-13 22:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fax',
            name='_from',
            field=models.CharField(default='+18728147688', max_length=16),
        ),
        migrations.AlterField(
            model_name='fax',
            name='sid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fax',
            name='twilio_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
