# Generated by Django 2.2.1 on 2019-05-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0003_auto_20190513_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='fax',
            name='error_message',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fax',
            name='fax_status',
            field=models.CharField(default='queued', max_length=16),
        ),
    ]
