# Generated by Django 2.2.1 on 2019-05-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0004_auto_20190513_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fax',
            name='direction',
            field=models.CharField(default='outbound', max_length=16),
        ),
    ]
