# Generated by Django 2.2.1 on 2019-05-14 01:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0005_auto_20190513_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fax',
            name='twilio_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
