# Generated by Django 2.2.1 on 2019-05-14 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0006_auto_20190514_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fax',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
